### ISSUE TITLE
mapstructure-to-hcl2: . . . Unexpected package creation during export data loading

### ISSUE THREAD

**Issue by NorseGaud** [hashicorp/packer-plugin-sdk#128]
#### Overview of the Issue

```bash
❯ make go.hcl2spec
GOOS=darwin go generate builder/anka/config.go
mapstructure-to-hcl2: anka.[Config PortForwardingRule]: Unexpected package creation during export data loading
builder/anka/config.go:1: running "packer-sdc": exit status 1
make: *** [go.hcl2spec] Error 1
```

Makefile:

```
install-packer-sdc:
	@go install github.com/hashicorp/packer-plugin-sdk/cmd/packer-sdc@${HASHICORP_PACKER_PLUGIN_SDK_VERSION}

#go.hcl2spec:		@ Run `go generate` to generate hcl2 config specs
go.hcl2spec: install-packer-sdc
	GOOS=$(OS_TYPE) go generate builder/anka/config.go
	GOOS=$(OS_TYPE) go generate post-processor/ankaregistry/post-processor.go
```

```
❯ packer-sdc --version 
0.3.1
```

```
❯ go version
go version go1.18.5 darwin/amd64
```

#### Reproduction Steps

Use something like `//go:generate packer-sdc mapstructure-to-hcl2 -type Config,PortForwardingRule` at the top of your go file.

This sort of came out of the blue and was working for quite a while in our CI/CD. Here are the changes we made: https://github.com/veertuinc/packer-plugin-veertu-anka/pull/127/files

**Comment by NorseGaud** [comment]
Nevermind. It's a problem with `github.com/zclconf/go-cty v1.11.0`

**Comment by NorseGaud** [comment]
Reopening due to comment in https://github.com/zclconf/go-cty/issues/132#issuecomment-1235736057

**Comment by dontlaugh** [comment]
See also: https://github.com/zclconf/go-cty/issues/134#issuecomment-1267124433

Seems tricky.

**Comment by nywilken** [comment]
This issue is being tracked in #135. Please feel free to reach out if you have any questions or concerns.
