### ISSUE TITLE
Upgrade github.com/zclconf/go-cty to v1.11.1

### ISSUE THREAD

**Issue by nywilken** [hashicorp/packer-plugin-sdk#135]
Upgrade github.com/zclconf/go-cty to v1.11.1

In v1.11.0 go-cty dropped all `encoding/gob` support - refer to [commit](https://github.com/zclconf/go-cty/commit/97bafac0dea33a3f74db88ab54dea2937b9e8aef) for details. 
Gob support is currently being used by the Datasource RPC server, and possiblity within other locations, for communication with the data source plugin components. Before upgrading
to the latest go-cty version the RPC serialization code must be updated to use a new serialization format or we can look into copying the encoding/gob support into 
the Packer SDK if there are no other options.

**Comment by NorseGaud** [comment]
bump

**Comment by lbajolet-hashicorp** [comment]
Hi @NorseGaud, sorry for taking a long time to address this.

We're still evaluating the kind of change needed for this update to be applicable to Packer, as Wilken mentions in the description for this issue, this change of the cty library removes support for `gob` encoding, which is what we use for the Packer->plugin communication, so this'll require some refactoring before we can bump it.

If possible, we want to avoid breaking communication between Packer and older versions of plugins that are installed, so we need to tread carefully, this will likely take some time before we land that change in the SDK, Packer, and the plugins.

We'll keep this issue updated with more information as we proceed with this change, and let you know when it's safe to bump cty everywhere.

Sorry for not bringing better news on that end, hopefully this won't be a blocker for you.

**Comment by nywilken** [comment]
In v1.11.0 of [github.com/zclconf/go-cty](https://github.com/zclconf/go-cty/blob/main/CHANGELOG.md#upgrade-notes-1), encoding/gob support was removed from the package. The Packer plugin SDK relies on gob for supporting HCL2 templates. The removal of the encoding causes Packer to crash when using HCL2 templates.


The team and I are working internally to find the best path forward, as a change to the wire protocol from gob to something else will introduce a breaking change and plugin incompatibilities. We are working to notify plugin developers of the incompatible go-cty package and ask that all external plugins pin to the versions of the following two packages to those used by the Packer plugin SDK.

[github.com/hashicorp/hcl/v2](http://github.com/hashicorp/hcl/v2) v2.13.0
[github.com/zclconf/go-cty](http://github.com/zclconf/go-cty) v1.10.0


 Feel free to reach out if you have any questions or concerns.

**Comment by nywilken** [comment]
Hi Folks - apologies for the long turn around time on this issue. We've been looking into options for resolving this issue that allows developers to upgrade, while providing a path forward for Packer's use of github.com/zclconf/go-cty. 

The issue #188 titled "The Path to Packer Plugin SDK v1.0.0" explains the issue we ran into with go-cty v1.11.0+ and outlines a plan forward for Packer. Please take a look and let us know if you have any questions, concerns, or suggestions. 

In the next SDK release slated for v0.5.0 we will provide a workaround to allow developers to upgrade go-cty and hcl/v2 dependencies. The first change for v0.5.0 being #186, which is captured in detailed in issue #187. 

The ultimate fix will happen in version 1.0.0 of the Packer SDK, which is to move off of `encoding/gob` as the wire protocol for Packer core and its plugins. 

I can't thank you enough for bubbling up this issue, and for being patient with us as we work to implement the next steps.

**Comment by mschuchard** [comment]
Thanks for the update, and would you consider this issue as also replacing the issue tracking within the `go-cty` repo for the issue I opened that is referenced in #131? I would like to close that one in the `go-cty` repo in favor of this one also.
