### ISSUE TITLE
Adding support for GCP Secrets Manager

### ISSUE THREAD

**Issue by dooman87** [hashicorp/packer-plugin-sdk#14]
Hi there,

Just wondering if it's a good idea to add `gcp_secretsmanager` function to HCL templates the same way `aws_secretsmanager` exists now.

If that's something Packer users could benefit from - I'm happy to make changes and raise a PR.

**Comment by SwampDragons** [comment]
I think it is a good idea, but I'd recommend holding off for a bit before adding it -- we're currently reworking the way the aws secretsmanager works to follow a "data source" pattern like Terraform uses for some of its input. Once that work has been ironed out, adding a secrets manager for google compute and other clouds will be a lot simpler.

**Comment by azr** [comment]
Hello there, I'm re-opening this issue over in https://github.com/hashicorp/packer-plugin-googlecompute . This should probably be implemented in the form of a new secrets manager datasource 🙂
