### ISSUE TITLE
ssh_certificate_file is wrongly used for ssh bastion

### ISSUE THREAD

**Issue by theblop** [hashicorp/packer-plugin-sdk#173]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

I'm not sure if this is an issue with packer or with the proxmox plugin, but it seems that there is a bug when `ssh_certificate_file` is specified for the build image at the same time as using a bastion host with no `ssh_bastion_certificate_file`.

In this case the ssh bastion key is wrongly signed with `ssh_certificate_file` :
```
* ssh_bastion_private_key_file is invalid: failed to create cert signer: ssh: signer and cert have different public key
```

I tried explicitly setting `ssh_bastion_certificate_file` to `null` but I get the same behaviour.

The only workaround I found was to configure an ssh CA cert on the bastion host and create a cert for the bastion key with that CA.

### Packer version

- packer v1.8.6
- github.com/hashicorp/proxmox 1.1.2

### Simplified Packer Template
```
source "proxmox-clone" "vm" {
  clone_vm = "my_image"
  ...
  ssh_username = "root"
  ssh_private_key_file = "./deploy.key"
  ssh_certificate_file = "./deploy.key-cert.pub"
  ssh_bastion_username = "packer"
  ssh_bastion_host = "bastion"
  ssh_bastion_private_key_file = "bastion.key"
  ssh_bastion_certificate_file = null
}
```

### Log Fragments and crash.log files

```
* ssh_bastion_private_key_file is invalid: failed to create cert signer: ssh: signer and cert have different public key
```

**Comment by nywilken** [comment]
Hi @theblop thanks for bubbling this issue up. The SSH bastion logic is handled by the SSH communicator. I've transferred the issue over to the appropriate repository. That said, looking at the [code](https://github.com/hashicorp/packer-plugin-sdk/blob/b03e2b6b7bbc38ca6b92770b33873860e796a5e0/communicator/config.go#L509) I see that the SSHCertificateFile will be used if the SSHBastionCertificateFile is not specified, which seems to be the issue. 

@lbajolet-hashicorp do you have any insight on this issue. It seems like a it might be a small change needed to get this working. 

@theblop if you are interested in opening a PR with the fix we would be happy to review.

**Comment by lbajolet-hashicorp** [comment]
I would think this is fixable, in this case I presume the workaround would be to only attempt to use the SSH certificate if the bastion SSH key is not set, since the other certificate should be linked to the SSH key we use for authenticate to the final host.

I'll open a PR shortly to change this.

**Comment by theblop** [comment]
> I would think this is fixable, in this case I presume the workaround would be to only attempt to use the SSH certificate if the bastion SSH key is not set, since the other certificate should be linked to the SSH key we use for authenticate to the final host.

I'm not sure if I understood your proposal correctly, but IMO the fix is simply to NEVER use `ssh_certificate_file` for the bastion ssh connection, since there is already a separate setting for the bastion cert if it needs it (`ssh_bastion_certificate_file`).

**Comment by lbajolet-hashicorp** [comment]
Oh I realise my usage of workaround was probably misplaced, in this case I meant fix. On your side directly I'm not sure you can do much besides using a certificate that matches the key you set for the bastion.

And while I understand your point about `ssh_bastion_certificate_file`, since right now if you specify a bastion host and no key, we default on using the ssh key, it makes sense to adapt the code to also use the certificate linked to that key if it is available.
What is problematic now is that the two entities are not set together, leading to the situation you are experiencing.

I have a commit on hand which I believe will fix your issue, I have to test it more thoroughly, but normally I should have a PR open today for this.
