### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by wdahlenburg** [hashicorp/packer-plugin-sdk#64]
#### Overview of the Issue

I'm working to upgrade a plugin manually and am running into issues with v0.2.0 of this SDK. 

The following error occurs  after running `go get .`

```
/Users/w/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.2.0/multistep/commonsteps/step_download.go:205:3: unknown field 'Mode' in struct literal of type getter.Request
```

The bug is in this line: https://github.com/hashicorp/packer-plugin-sdk/blob/main/multistep/commonsteps/step_download.go#L205

It appears that the [getter](https://github.com/hashicorp/go-getter) object no longer has a ModeFile attribute. This appears to be breaking installs that make use of "github.com/hashicorp/packer-plugin-sdk/multistep/commonsteps"

#### Reproduction Steps

Compile a plugin that imports "github.com/hashicorp/packer-plugin-sdk/multistep/commonsteps".

### Packer Plugin SDK version

v0.2.0

### Operating system and Environment details

Go 1.16 on OSX and Ubuntu

**Comment by azr** [comment]
Hello there, thanks for opening, this should have started happening after the go-getter/v2 got tagged with v2.0.0. I'll update the dep, fix the usage and cut a new release.

**Comment by azr** [comment]
Okay, I just released a new version of this sdk, you can fix this by running `go get github.com/hashicorp/packer-plugin-sdk@v0.2.1` and maybe `go get -u .`. Thanks again for opening ! 👋🏼
