### ISSUE TITLE
ssh_timeout not working windows and wsl

### ISSUE THREAD

**Issue by todeb** [hashicorp/packer-plugin-sdk#87]
Hello,

seems that "ssh_timeout" property is not working using packer on wsl2 and on windows.
I had set: ssh_timeout = "30m"

I had tried to find workaroud eg. setting:
ssh_proxy_host = "127.0.0.1"
then it waits 30min but it is not connecting.
I have ssh server running locally and I had added my public key to authorized keys. I'm able to ssh 127.0.01 without password.
Is there anything more that should i configure?

**Comment by unbreakabl3** [comment]
I have the same issue. The workaround with increasing `ssh_handshake_attempts` did work for me as well. I am running Packer 1.8.0

**Comment by rlaun** [comment]
Same on an Ubuntu 18.04 host running Packer 1.8.0, it seems like `ssh_timeout` is ignored. The workaround with `ssh_handshake_attempts` works though.
